### ISSUE TITLE
add font variable

### ISSUE THREAD

**Issue by lsfgrd** [lsfgrd/uebersicht_italian-word#1]
**THE ISSUE:**
wELP, my intention was to add a font-family variable to the script, but I ended up forgetting to do so.

Since it's Hacktoberfest, I decided to open this issue.

**And this is a beginners-only event!**

-----------

There are plenty of examples in the CoffeeScript file on how to set up the variables (top, left, max_width, font_color, background). Just don't forget to reference it in the CSS, at the "style" section.

Oh, and, please: keep the **snake_case** standard!

**Comment by luizamunk** [comment]
Maybe I can do it! =D

**Comment by lsfgrd** [comment]
Done.
